---
jenkins_home: /var/lib/jenkins
jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_repo_url: https://pkg.jenkins.io/redhat/jenkins.repo
jenkins_repo_key_url: https://pkg.jenkins.io/redhat/jenkins.io.key
jenkins_pkg_url: https://pkg.jenkins.io/redhat
jenkins_package_state: present